version: 2.1
jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  secret_scanning:
    machine: true
    steps:
      - run:
          command: |
            echo "my artifact file" > /tmp/myfile.txt
            exit 1
            when: on_fail
      - store_artifacts:
          path: /tmp/myfile.txt
          destination: artifact-file
          
  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
          when: always
  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step."

workflows:
  version: 2
  django:
    jobs:
      - build
      - secret_scanning:
          requires:
            - build
      - integration:
          requires:
            - secret_scanning
      - prod:
          type: approval
          requires:
            - integration